---



# -------------------------------------------------------------------
cora:      # 使用Cora数据集训练模型
# -------------------------------------------------------------------
    random_state:            42          # 随机种子
    model:                               # 模型参数
        input_dim:           1433          # 节点特征维度
        hidden_dims:         [128, 7]      # 隐层输出特征维度
        num_neighbors_list:  [10, 10]      # 每阶采样邻居的节点数
    hyper:                               # 训练超参数
        lr:                  0.003         # 优化器初始学习率
        epochs:              20            # 训练轮次
        batch_size:          16            # 批数据大小
        weight_decay:        0.0005        # 优化器权重衰减
        num_batch_per_epoch: 20            # 每个epoch循环的批次数



# -------------------------------------------------------------------
pubmed:    # 使用Pubmed数据集训练模型
# -------------------------------------------------------------------
    random_state:            42          # 随机种子
    model:                               # 模型参数
        input_dim:           500           # 节点特征维度
        hidden_dims:         [128, 3]      # 隐层输出特征维度
        num_neighbors_list:  [10, 10]      # 每阶采样邻居的节点数
    hyper:                               # 训练超参数
        lr:                  0.003         # 优化器初始学习率
        epochs:              20            # 训练轮次
        batch_size:          16            # 批数据大小
        weight_decay:        0.0005        # 优化器权重衰减
        num_batch_per_epoch: 20            # 每个epoch循环的批次数



# -------------------------------------------------------------------
citeseer:  # 使用Citeseer数据集训练模型
# -------------------------------------------------------------------
    random_state:            42          # 随机种子
    model:                               # 模型参数
        input_dim:           3703          # 节点特征维度
        hidden_dims:         [128, 6]      # 隐层输出特征维度
        num_neighbors_list:  [10, 10]      # 每阶采样邻居的节点数
    hyper:                               # 训练超参数
        lr:                  0.003         # 优化器初始学习率
        epochs:              20            # 训练轮次
        batch_size:          16            # 批数据大小
        weight_decay:        0.0005        # 优化器权重衰减
        num_batch_per_epoch: 20            # 每个epoch循环的批次数



...