---



# -------------------------------------------------------------------
DD:      # 使用DD数据集训练模型
# -------------------------------------------------------------------
    random_state:     42          # 随机种子
    split:                        # 数据划分
        test_prop:    0.2           # 测试集数据比例
        valid_prop:   0.1           # 验证集数据比例
    model:                        # 模型参数
        dropout:      0.2           # dropout比例
        use_bias:     True          # 是否使用偏置
        aggregate:    'sum'         # 节点特征聚合方式
        input_dim:    89            # 节点特征维度
        output_dim:   2             # 节点类别数
        hidden_dim:   16            # 隐层输出特征维度
    hyper:                        # 训练超参数
        lr:           0.001         # 优化器初始学习率
        epochs:       20            # 训练轮次
        patience:     50            # 早停轮次
        batch_size:   8             # 批数据数量
        weight_decay: 0.0005        # 优化器权重衰减



# -------------------------------------------------------------------
NCI1:      # 使用NCI1数据集训练模型
# -------------------------------------------------------------------
    random_state:     42          # 随机种子
    split:                        # 数据划分
        test_prop:    0.2           # 测试集数据比例
        valid_prop:   0.1           # 验证集数据比例
    model:                        # 模型参数
        dropout:      0.2           # dropout比例
        use_bias:     True          # 是否使用偏置
        aggregate:    'sum'         # 节点特征聚合方式
        input_dim:    37            # 节点特征维度
        output_dim:   2             # 节点类别数
        hidden_dim:   64            # 隐层输出特征维度
    hyper:                        # 训练超参数
        lr:           0.001         # 优化器初始学习率
        epochs:       1000          # 训练轮次
        patience:     50            # 早停轮次
        batch_size:   64            # 批数据数量
        weight_decay: 0.0005        # 优化器权重衰减



# -------------------------------------------------------------------
PROTEINS:      # 使用PROTEINS数据集训练模型
# -------------------------------------------------------------------
    random_state:     42          # 随机种子
    split:                        # 数据划分
        test_prop:    0.2           # 测试集数据比例
        valid_prop:   0.1           # 验证集数据比例
    model:                        # 模型参数
        dropout:      0.2           # dropout比例
        use_bias:     True          # 是否使用偏置
        aggregate:    'sum'         # 节点特征聚合方式
        input_dim:    4             # 节点特征维度
        output_dim:   2             # 节点类别数
        hidden_dim:   32            # 隐层输出特征维度
    hyper:                        # 训练超参数
        lr:           0.0001        # 优化器初始学习率
        epochs:       1000          # 训练轮次
        patience:     50            # 早停轮次
        batch_size:   32            # 批数据数量
        weight_decay: 0.0005        # 优化器权重衰减


...