---



# -------------------------------------------------------------------
cora:      # 使用Cora数据集训练模型
# -------------------------------------------------------------------
    random_state:     42          # 随机种子
    model:                          # 模型参数
        dropout:      0.0           # dropout比例
        use_bias:     True          # 是否使用偏置
        input_dim:    1433          # 节点特征维度
        output_dim:   7             # 节点类别数
        hidden_dim:   16            # 隐层输出特征维度
    hyper:                        # 训练超参数
        lr:           0.01          # 优化器初始学习率
        epochs:       100           # 训练轮次
        batch_size:   64            # 批数据数量
        weight_decay: 0.0005        # 优化器权重衰减
        sampler_dims: [128, 128]    # 每层网络采样节点个数



# -------------------------------------------------------------------
pubmed:    # 使用Pubmed数据集训练模型
# -------------------------------------------------------------------
    random_state:     42          # 随机种子
    model:                        # 模型参数
        dropout:      0.0           # dropout比例
        use_bias:     True          # 是否使用偏置
        input_dim:    500           # 节点特征维度
        output_dim:   3             # 节点类别数
        hidden_dim:   16            # 隐层输出特征维度
    hyper:                        # 训练超参数
        lr:           0.01          # 优化器初始学习率
        epochs:       100           # 训练轮次
        batch_size:   64            # 批数据数量
        weight_decay: 0.0005        # 优化器权重衰减
        sampler_dims: [128, 128]    # 每层网络采样节点个数



# -------------------------------------------------------------------
citeseer:  # 使用Citeseer数据集训练模型
# -------------------------------------------------------------------
    random_state:     42          # 随机种子
    model:                        # 模型参数
        dropout:      0.0           # dropout比例
        use_bias:     True          # 是否使用偏置
        input_dim:    3703          # 节点特征维度
        output_dim:   6             # 节点类别数
        hidden_dim:   16            # 隐层输出特征维度
    hyper:                        # 训练超参数
        lr:           0.01          # 优化器初始学习率
        epochs:       200           # 训练轮次
        batch_size:   64            # 批数据数量
        weight_decay: 0.0005        # 优化器权重衰减
        sampler_dims: [128, 128]    # 每层网络采样节点个数



...